name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gerar gráfico 3D
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D profile"
          git push
